import type { Metadata } from "next";
import { Bricolage_Grotesque, Instrument_Sans, JetBrains_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import SiteTerminal from "@/components/SiteTerminal";
import { SpeedInsights } from "@vercel/speed-insights/next";
import { themeInitScript } from "@/lib/theme";

// Display: Bricolage Grotesque — hand-cut terminals and wonky details that
// match the drawn contour motifs; characterful without being a novelty face.
const bricolage = Bricolage_Grotesque({
  subsets: ["latin"],
  weight: ["500", "600", "700"],
  variable: "--font-display",
  display: "swap",
});

// Body: Instrument Sans — warm, quietly quirky, disappears at text sizes.
const instrument = Instrument_Sans({
  subsets: ["latin"],
  weight: ["400", "500", "600"],
  variable: "--font-sans",
  display: "swap",
});

const jetbrainsMono = JetBrains_Mono({
  subsets: ["latin"],
  weight: ["400", "500"],
  variable: "--font-mono",
  display: "swap",
});

export const metadata: Metadata = {
  metadataBase: new URL("https://hjhportfolio.com"),
  title: "Harvey Houlahan — ML Systems · Simulation · Spatial Engineer",
  description:
    "ML engineer who ships: satellite and LiDAR pipelines measuring forest carbon in production, a 40M-parameter pretraining study, and GPU physics engines that run in the browser. Open for contract work. Byron Bay, remote.",
  keywords: [
    "ML Systems Engineer",
    "AI Integration",
    "RAG Pipelines",
    "LLM Fine-tuning",
    "Vector Databases",
    "Model Quantization",
    "Edge AI",
    "Geospatial ML",
    "PostGIS",
    "MapLibre GL JS",
    "FastAPI",
    "Carbon MRV",
    "Earth Observation",
    "Climate Tech",
    "Spatial Data Infrastructure",
  ],
  authors: [{ name: "Harvey Houlahan" }],
  alternates: {
    canonical: "https://hjhportfolio.com",
  },
  openGraph: {
    title: "Harvey Houlahan — ML Systems · Simulation · Spatial Engineer",
    description:
      "ML engineer who ships: satellite and LiDAR pipelines measuring forest carbon in production, a 40M-parameter pretraining study, and GPU physics engines that run in the browser. Open for contract work. Byron Bay, remote.",
    url: "https://hjhportfolio.com",
    siteName: "Harvey Houlahan",
    type: "website",
    locale: "en_AU",
    // OG image + its alt text are generated by app/opengraph-image.tsx
  },
  twitter: {
    card: "summary_large_image",
    title: "Harvey Houlahan — ML Systems · Simulation · Spatial Engineer",
    description:
      "ML engineer who ships: satellite and LiDAR pipelines measuring forest carbon in production, a 40M-parameter pretraining study, and GPU physics engines that run in the browser. Open for contract work. Byron Bay, remote.",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${bricolage.variable} ${instrument.variable} ${jetbrainsMono.variable}`}
      suppressHydrationWarning
    >
      <head>
        <script dangerouslySetInnerHTML={{ __html: themeInitScript }} />
      </head>
      <body>
        <div className="flex min-h-screen flex-col">
          <Navbar />
          <main className="flex-grow">{children}</main>
          <Footer />
        </div>
        <SiteTerminal />
        <SpeedInsights />
      </body>
    </html>
  );
}
