import type { Metadata } from "next";
import { Playfair_Display, Inter, JetBrains_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { SpeedInsights } from "@vercel/speed-insights/next";

const playfair = Playfair_Display({
  subsets: ["latin"],
  weight: ["400", "500", "600"],
  variable: "--font-display",
  display: "swap",
});

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
  display: "swap",
});

const jetbrainsMono = JetBrains_Mono({
  subsets: ["latin"],
  weight: ["400", "500"],
  variable: "--font-mono",
  display: "swap",
});

export const metadata: Metadata = {
  metadataBase: new URL("https://hjhportfolio.com"),
  title: "Harvey Houlahan — Spatial · Simulation · ML Engineer",
  description:
    "Production spatial systems and simulations for climate, carbon & nature tech. Available for contract work. Byron Bay · remote.",
  keywords: [
    "Geospatial ML",
    "PostGIS",
    "MapLibre GL JS",
    "FastAPI",
    "Carbon MRV",
    "Earth Observation",
    "Climate Tech",
    "Spatial Data Infrastructure",
  ],
  authors: [{ name: "Harvey Houlahan" }],
  alternates: {
    canonical: "https://hjhportfolio.com",
  },
  openGraph: {
    title: "Harvey Houlahan — Spatial · Simulation · ML Engineer",
    description:
      "Production spatial systems and simulations for climate, carbon & nature tech. Available for contract work. Byron Bay · remote.",
    url: "https://hjhportfolio.com",
    siteName: "Harvey Houlahan",
    type: "website",
    locale: "en_AU",
    // OG image + its alt text are generated by app/opengraph-image.tsx
  },
  twitter: {
    card: "summary_large_image",
    title: "Harvey Houlahan — Spatial · Simulation · ML Engineer",
    description:
      "Production spatial systems and simulations for climate, carbon & nature tech. Available for contract work. Byron Bay · remote.",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${playfair.variable} ${inter.variable} ${jetbrainsMono.variable}`}
    >
      <body>
        <div className="flex min-h-screen flex-col">
          <Navbar />
          <main className="flex-grow">{children}</main>
          <Footer />
        </div>
        <SpeedInsights />
      </body>
    </html>
  );
}
